export const SYMPTOM_OPTIONS: { key: string; label: string }[] = [
  { key: 'cramps', label: 'Cramps' },
  { key: 'bloating', label: 'Bloating' },
  { key: 'headache', label: 'Headache' },
  { key: 'fatigue', label: 'Fatigue' },
  { key: 'nausea', label: 'Nausea' },
  { key: 'backache', label: 'Backache' },
  { key: 'breast_tenderness', label: 'Breast Tenderness' },
  { key: 'acne', label: 'Acne' },
  { key: 'mood_swings', label: 'Mood Swings' },
  { key: 'insomnia', label: 'Insomnia' },
  { key: 'cravings', label: 'Cravings' },
  { key: 'dizziness', label: 'Dizziness' },
  { key: 'hot_flashes', label: 'Hot Flashes' },
  { key: 'spotting', label: 'Spotting' },
  { key: 'constipation', label: 'Constipation' },
  { key: 'diarrhea', label: 'Diarrhea' },
  { key: 'anxiety', label: 'Anxiety' },
  { key: 'irritability', label: 'Irritability' },
  { key: 'low_libido', label: 'Low Libido' },
  { key: 'pelvic_pain', label: 'Pelvic Pain' },
] as const;
