"""Sync all models to current DB schema.

Autogenerated from model-vs-DB diff, then hand-edited for safety:

- Added server_default=true for is_active columns (prevent NOT NULL violations on existing rows)
- Added server_default=gen_random_uuid() for system_config.id
- Replaced ENUM alter_column with ALTER TYPE RENAME (values unchanged)
- Changed system_config.id to nullable then backfilled (safe for empty dev DB)
- Removed system_config.id add_column in favor of add-then-alter pattern
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93a7172745d5'
down_revision: Union[str, None] = '0017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_index(op.f('ix_audit_logs_is_active'), 'audit_logs', ['is_active'], unique=False)
    op.create_index(op.f('ix_chat_invites_is_active'), 'chat_invites', ['is_active'], unique=False)
    op.alter_column('cycle_entries', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_cycle_entries_user_period'), table_name='cycle_entries')
    op.create_index(op.f('ix_cycle_entries_is_active'), 'cycle_entries', ['is_active'], unique=False)
    op.create_index(op.f('ix_cycle_entries_user_id'), 'cycle_entries', ['user_id'], unique=False)
    op.execute("ALTER TABLE educational_contents ALTER COLUMN tags DROP DEFAULT")
    op.alter_column('educational_contents', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.JSON(),
               postgresql_using="to_json(tags)::json",
               existing_nullable=False,
               existing_server_default=None)
    op.execute("ALTER TABLE educational_contents ALTER COLUMN tags SET DEFAULT '[]'::json")
    op.create_index(op.f('ix_educational_contents_is_active'), 'educational_contents', ['is_active'], unique=False)
    op.create_index(op.f('ix_educational_contents_nurse_id'), 'educational_contents', ['nurse_id'], unique=False)
    op.drop_index(op.f('ix_emergency_contacts_user_primary'), table_name='emergency_contacts')
    op.alter_column('family_links', 'linked_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_family_links_is_active'), 'family_links', ['is_active'], unique=False)
    op.create_index(op.f('ix_family_links_linked_user_id'), 'family_links', ['linked_user_id'], unique=False)
    op.create_index(op.f('ix_family_links_user_id'), 'family_links', ['user_id'], unique=False)
    op.add_column('journal_analyses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('journal_analyses', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('journal_analyses', 'is_active', server_default=None)
    op.create_index(op.f('ix_journal_analyses_is_active'), 'journal_analyses', ['is_active'], unique=False)
    op.alter_column('journal_entries', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_journal_entries_user_date'), table_name='journal_entries')
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.alter_column('mood_logs', 'intensity',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'3'::smallint"))
    op.drop_index(op.f('ix_mood_logs_user_logged'), table_name='mood_logs')
    op.create_index(op.f('ix_mood_logs_user_id'), 'mood_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_nurse_profiles_is_active'), 'nurse_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_predicted_cycles_is_active'), 'predicted_cycles', ['is_active'], unique=False)
    op.create_index(op.f('ix_predicted_cycles_user_id'), 'predicted_cycles', ['user_id'], unique=False)
    op.alter_column('pregnancy_daily_logs', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_preg_daily_logs_preg_date'), table_name='pregnancy_daily_logs')
    op.create_index(op.f('ix_pregnancy_daily_logs_is_active'), 'pregnancy_daily_logs', ['is_active'], unique=False)
    op.create_index(op.f('ix_pregnancy_daily_logs_pregnancy_id'), 'pregnancy_daily_logs', ['pregnancy_id'], unique=False)
    op.alter_column('pregnancy_milestones', 'development_tip',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_pregnancy_milestones_week'), table_name='pregnancy_milestones')
    op.create_index(op.f('ix_pregnancy_milestones_is_active'), 'pregnancy_milestones', ['is_active'], unique=False)
    op.drop_constraint(op.f('uq_pregnancy_profiles_user_id'), 'pregnancy_profiles', type_='unique')
    op.create_index(op.f('ix_pregnancy_profiles_is_active'), 'pregnancy_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_pregnancy_profiles_user_id'), 'pregnancy_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_snooze_events_is_active'), 'snooze_events', ['is_active'], unique=False)
    # ENUM rename: values unchanged, type name updated to match model
    op.execute("ALTER TYPE sos_trigger_source RENAME TO trigger_source")
    op.drop_index(op.f('ix_sos_alerts_user_triggered'), table_name='sos_alerts')
    op.create_index(op.f('ix_sos_alerts_is_active'), 'sos_alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_sos_alerts_user_id'), 'sos_alerts', ['user_id'], unique=False)
    op.alter_column('sos_notification_attempts', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_sos_notification_attempts_is_active'), 'sos_notification_attempts', ['is_active'], unique=False)
    op.create_index(op.f('ix_sos_notification_attempts_sos_alert_id'), 'sos_notification_attempts', ['sos_alert_id'], unique=False)
    # system_config: add Base columns with safe defaults
    op.add_column('system_config', sa.Column('id', sa.UUID(), nullable=True))
    op.execute("UPDATE system_config SET id = gen_random_uuid() WHERE id IS NULL")
    op.alter_column('system_config', 'id', nullable=False)
    op.add_column('system_config', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('system_config', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('system_config', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('system_config', 'is_active', server_default=None)
    op.create_index(op.f('ix_system_config_is_active'), 'system_config', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_consents_is_active'), 'user_consents', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_exercise_sessions_exercise_id'), 'user_exercise_sessions', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_user_exercise_sessions_is_active'), 'user_exercise_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_exercise_sessions_user_id'), 'user_exercise_sessions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_onboarding_user_id'), table_name='user_onboarding')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.alter_column('users', 'medical_notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_users_phone_number'), 'users', type_='unique')


def downgrade() -> None:
    op.create_unique_constraint(op.f('uq_users_phone_number'), 'users', ['phone_number'])
    op.alter_column('users', 'medical_notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_user_onboarding_user_id'), 'user_onboarding', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_exercise_sessions_user_id'), table_name='user_exercise_sessions')
    op.drop_index(op.f('ix_user_exercise_sessions_is_active'), table_name='user_exercise_sessions')
    op.drop_index(op.f('ix_user_exercise_sessions_exercise_id'), table_name='user_exercise_sessions')
    op.drop_index(op.f('ix_user_consents_is_active'), table_name='user_consents')
    op.drop_index(op.f('ix_system_config_is_active'), table_name='system_config')
    op.drop_column('system_config', 'is_active')
    op.drop_column('system_config', 'updated_at')
    op.drop_column('system_config', 'created_at')
    op.drop_column('system_config', 'id')
    op.drop_index(op.f('ix_sos_notification_attempts_sos_alert_id'), table_name='sos_notification_attempts')
    op.drop_index(op.f('ix_sos_notification_attempts_is_active'), table_name='sos_notification_attempts')
    op.alter_column('sos_notification_attempts', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_sos_alerts_user_id'), table_name='sos_alerts')
    op.drop_index(op.f('ix_sos_alerts_is_active'), table_name='sos_alerts')
    op.create_index(op.f('ix_sos_alerts_user_triggered'), 'sos_alerts', ['user_id', 'triggered_at'], unique=False)
    op.execute("ALTER TYPE trigger_source RENAME TO sos_trigger_source")
    op.drop_index(op.f('ix_snooze_events_is_active'), table_name='snooze_events')
    op.drop_index(op.f('ix_pregnancy_profiles_user_id'), table_name='pregnancy_profiles')
    op.drop_index(op.f('ix_pregnancy_profiles_is_active'), table_name='pregnancy_profiles')
    op.create_unique_constraint(op.f('uq_pregnancy_profiles_user_id'), 'pregnancy_profiles', ['user_id'])
    op.drop_index(op.f('ix_pregnancy_milestones_is_active'), table_name='pregnancy_milestones')
    op.create_index(op.f('ix_pregnancy_milestones_week'), 'pregnancy_milestones', ['week'], unique=False)
    op.alter_column('pregnancy_milestones', 'development_tip',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_pregnancy_daily_logs_pregnancy_id'), table_name='pregnancy_daily_logs')
    op.drop_index(op.f('ix_pregnancy_daily_logs_is_active'), table_name='pregnancy_daily_logs')
    op.create_index(op.f('ix_preg_daily_logs_preg_date'), 'pregnancy_daily_logs', ['pregnancy_id', 'log_date'], unique=False)
    op.alter_column('pregnancy_daily_logs', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_predicted_cycles_user_id'), table_name='predicted_cycles')
    op.drop_index(op.f('ix_predicted_cycles_is_active'), table_name='predicted_cycles')
    op.drop_index(op.f('ix_nurse_profiles_is_active'), table_name='nurse_profiles')
    op.drop_index(op.f('ix_mood_logs_user_id'), table_name='mood_logs')
    op.create_index(op.f('ix_mood_logs_user_logged'), 'mood_logs', ['user_id', 'logged_at'], unique=False)
    op.alter_column('mood_logs', 'intensity',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'3'::smallint"))
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.create_index(op.f('ix_journal_entries_user_date'), 'journal_entries', ['user_id', 'entry_date'], unique=False)
    op.alter_column('journal_entries', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_journal_analyses_is_active'), table_name='journal_analyses')
    op.drop_column('journal_analyses', 'is_active')
    op.drop_column('journal_analyses', 'updated_at')
    op.drop_index(op.f('ix_family_links_user_id'), table_name='family_links')
    op.drop_index(op.f('ix_family_links_linked_user_id'), table_name='family_links')
    op.drop_index(op.f('ix_family_links_is_active'), table_name='family_links')
    op.alter_column('family_links', 'linked_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_emergency_contacts_user_primary'), 'emergency_contacts', ['user_id', 'is_primary'], unique=False)
    op.drop_index(op.f('ix_educational_contents_nurse_id'), table_name='educational_contents')
    op.drop_index(op.f('ix_educational_contents_is_active'), table_name='educational_contents')
    op.alter_column('educational_contents', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.drop_index(op.f('ix_cycle_entries_user_id'), table_name='cycle_entries')
    op.drop_index(op.f('ix_cycle_entries_is_active'), table_name='cycle_entries')
    op.create_index(op.f('ix_cycle_entries_user_period'), 'cycle_entries', ['user_id', 'period_start_date'], unique=False)
    op.alter_column('cycle_entries', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_chat_invites_is_active'), table_name='chat_invites')
    op.drop_index(op.f('ix_audit_logs_is_active'), table_name='audit_logs')
